import type {Metadata} from 'next';

export const metadata:Metadata={
  title:'How We Build Greener | Sustainable Construction Essex',
  description:'See how The Keystone Eco Group applies practical greener choices to extensions, renovations and construction: lower-impact materials, reuse, energy, water and waste.',
  alternates:{canonical:'/how-we-build-greener'},
  openGraph:{title:'How We Build Greener | The Keystone Eco Group',description:'Practical sustainable construction choices without reinventing the way good buildings are built.',url:'/how-we-build-greener'}
};

const choices=[
  ['Foundations & concrete','Where the design and engineering allow, we look at reducing unnecessary concrete, appropriate lower-carbon concrete specifications and reusing suitable excavated material rather than automatically sending it off site.'],
  ['Structure & timber','We can specify responsibly sourced FSC- or PEFC-certified timber, consider timber framing where appropriate, use reclaimed structural timber where it can be properly assessed or graded, and design around standard material sizes to reduce waste.'],
  ['External walls','Options can include timber-frame construction, wood-fibre or cellulose insulation, reclaimed or locally sourced brick and stone, lime mortar and breathable wall build-ups where these suit the building and technical requirements.'],
  ['Insulation','Alongside conventional insulation, we can consider materials such as wood fibre, cellulose made from recycled paper, cork, hemp and sheep wool where their thermal, fire, moisture and installation characteristics make them appropriate.'],
  ['Plaster & finishes','Lime or clay plaster can provide an alternative to automatically using gypsum everywhere, particularly where a breathable construction is desirable. Low-VOC paints and finishes can also be considered.'],
  ['Flooring','We can look at reclaimed floorboards or parquet, certified timber, cork, linoleum, recycled-content tiles and restoration of an existing floor before deciding that it needs replacing.'],
  ['Roofing','A roof can combine reclaimed tiles or slates where suitable, responsibly sourced timber, high levels of insulation and good airtightness. Appropriate projects can also consider solar PV, green roofs and rainwater collection.'],
  ['Windows & doors','Sometimes retaining and improving existing joinery makes more sense than replacing it. Where new units are required, we can consider high-performance timber or composite products alongside glazing, draught sealing and thermal-bridge details.'],
  ['Kitchens & interiors','Existing cabinets may be reusable or suitable for refacing. Other options include reclaimed timber, certified timber cabinetry, recycled-content surfaces and lower-impact finishes.'],
  ['Heating & energy','Depending on the property, we can consider lower-temperature heating, heat pumps, solar PV, battery storage, smart heating zones, LED lighting and energy monitoring as part of the wider building strategy.'],
  ['Water & landscaping','Low-flow fittings, dual-flush WCs, rainwater collection, permeable landscaping and water butts are straightforward options. More involved rainwater-reuse systems can also be considered where correctly designed for their intended use.'],
  ['Waste & reuse','We favour careful strip-out where practical: salvaging useful bricks, timber, slates and fittings, separating waste streams and ordering accurately to reduce skips, surplus material and unnecessary disposal.']
];

export default function Greener(){return <main className="green-build-page">
<section className="green-build-hero"><div><span className="eyebrow">HOW WE ARE GREEN</span><h1>Good building.<br/><em>Better choices.</em></h1><p>Sustainable construction does not have to mean reinventing the way a building is built. For us, it means applying practical experience and asking a better question at every stage: is there a lower-impact, healthier, reclaimed, responsibly sourced or more energy-efficient way to achieve the same objective?</p><a className="hero-primary" href="/contact">Discuss your project →</a></div></section>
<section className="green-build-intro"><div><span className="construction-eyebrow">OUR APPROACH</span><h2>We don't make a building “eco” for the sake of a label.</h2></div><div><p>We build conventionally where that makes sense. At specification stage, we identify opportunities to reduce waste, reuse what already exists, select lower-impact alternatives and improve the finished building's energy performance.</p><p>That could be as simple as specifying certified timber or restoring an existing floor. On another project it might involve natural insulation, lime plaster, solar generation, battery storage or a complete fabric-and-energy strategy.</p><blockquote>Sometimes the greenest option is simple: <strong>don't replace it. Repair it.</strong></blockquote></div></section>
<section className="green-build-choices"><div className="construction-section-heading"><span className="construction-eyebrow">FROM FOUNDATIONS TO FINISHES</span><h2>Where greener choices can be made</h2><p>The right option depends on the building, budget, design, regulations and technical requirements.</p></div><div className="green-choice-grid">{choices.map(([title,copy],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="green-build-levels"><div className="construction-section-heading"><span className="construction-eyebrow">YOU CHOOSE HOW FAR TO GO</span><h2>Three ways to approach a project</h2><p>Not every client wants or needs the same level of intervention. We can discuss the balance between cost, practicality, performance and environmental impact.</p></div><div className="green-level-grid"><article><span>01</span><h3>Standard</h3><p>A conventional, compliant build using proven methods and materials, with sensible attention to efficiency and waste.</p></article><article><span>02</span><h3>Eco Enhanced</h3><p>Targeted substitutions and improvements where they make sense — for example certified timber, reclaimed materials, alternative insulation, lime finishes and better-performing components.</p></article><article><span>03</span><h3>Eco+</h3><p>A whole-building conversation covering fabric, insulation, airtightness, heating, renewable energy, battery storage, water, materials and waste.</p></article></div></section>
<section className="green-build-principle"><div><span className="construction-eyebrow">PRACTICAL, NOT DOGMATIC</span><h2>The greenest material isn't automatically the right material.</h2><p>Every alternative still has to work. Fire safety, structural performance, moisture management, durability, Building Regulations, manufacturer requirements, availability and cost all matter. We recommend considering the whole building rather than swapping products simply because they are marketed as “eco”.</p><p>Our aim is straightforward: <strong>build well, waste less, retain more and make better material and energy choices where they genuinely benefit the project.</strong></p><div className="green-build-links"><a className="hero-primary" href="/contact">Talk to us about your project →</a><a className="construction-outline-link" href="/sustainable-materials">Explore sustainable materials →</a></div></div></section>
</main>}