'use client';
import {useState} from 'react';
const categories=['All','Construction','Green Technologies','Sustainable Materials','Developments'] as const;
const divisionLinks:Record<string,string>={'Construction':'/construction','Green Technologies':'/green-technologies','Sustainable Materials':'/sustainable-materials','Developments':'/developments'};
const photos=[
{category:'Construction',title:'Contemporary residential architecture',id:'photo-1600585154340-be6161a56a0c'},
{category:'Construction',title:'Modern living spaces',id:'photo-1600607687920-4e2a09cf159d'},
{category:'Green Technologies',title:'Solar energy inspiration',id:'photo-1509391366360-2e959784a276'},
{category:'Sustainable Materials',title:'Natural finishes and craftsmanship',id:'photo-1600566753190-17f0baa2a6c3'},
{category:'Developments',title:'Contemporary property design',id:'photo-1600596542815-ffad4c1539a9'},
{category:'Sustainable Materials',title:'Considered interior materials',id:'photo-1600566753086-00f18fb6b3ea'}];
export default function Gallery(){const [filter,setFilter]=useState<string>('All');const visible=photos.filter(p=>filter==='All'||p.category===filter);return <main><section className="pagehead galleryhead"><span className="eyebrow">DESIGN & ARCHITECTURAL INSPIRATION</span><h1>Explore our vision.</h1><p>A visual introduction to the design, materials and spaces that inspire our approach. These images illustrate the style and ideas behind our four divisions; they are not a portfolio of completed Keystone projects.</p></section><section className="wrap"><div className="gallerytoolbar"><div><span className="eyebrow">THE GALLERY</span><h2>Built to inspire.</h2></div><div className="galleryfilters" aria-label="Filter gallery">{categories.map(c=><button key={c} type="button" aria-pressed={filter===c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div></div><div className="gallerycards">{visible.map(p=><article className="gallerycard" key={p.id}><img loading="lazy" src={'https://images.unsplash.com/'+p.id+'?auto=format&fit=crop&w=1100&q=85'} alt={'Illustrative image: '+p.title}/><div><span>{p.category}</span><h3>{p.title}</h3><a className="gallery-division-link" href={divisionLinks[p.category]}>Explore {p.category} →</a></div></article>)}</div><p className="gallerydisclaimer">These are illustrative architectural photographs, not completed Keystone Eco Group projects. Genuine case studies and client-approved photographs will be added separately.</p></section><section className="closing"><span className="eyebrow">YOUR PROJECT, OUR NEXT CONVERSATION</span><h2>Have something in mind?</h2><p>Tell us what you are planning in Essex or elsewhere in the UK.</p><a className="button" href="/contact">Discuss your project ↗</a></section></main>}